# Generated by Django 4.0.6 on 2022-07-27 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=0),
            preserve_default=False,
        ),
    ]
